---@meta

--- A user-facing string. Either a plain string, or a localization table keyed by the game's language
--- folder codes (en, de, el, es, fr, it, ja, ko, pl, pt-BR, ru, tr, uk, zh-CN, zh-TW). It is resolved
--- to the current game language when the menu is shown, falling back to English.
--- Example: `{ en = "Difficulty", de = "Schwierigkeit" }`
---@alias mod_settings.localized_string string | table<string, string>

--- Most fields can also be dynamically resolved through a function call, which is evaluated when the
--- menu is opened and refreshed (after any other setting is changed).
---@alias mod_settings.dynamic_number number | fun(): number
---@alias mod_settings.dynamic_boolean boolean | fun(): boolean
---@alias mod_settings.dynamic_string mod_settings.localized_string | fun(): mod_settings.localized_string

--- Describes how a config option appears in the in-game mod settings menu. Every field is optional. The
--- widget type is inferred from the setting's config value (a boolean becomes a toggle; a number with `min`
--- and `max` becomes a slider; a value with `values` becomes a cycler; anything else is a free-text field).
---@class (exact) mod_settings.setting_description
--- Help text shown at the bottom of the options menu while the config rows is highlighted. Recommended to keep
--- to about 35 characters so it leaves enough space for free-text input strings.
---@field description? mod_settings.dynamic_string
--- Row label. Defaults to a prettified version of the config key (e.g. `myCool_Setting` -> "My Cool Setting").
---@field displayName? mod_settings.dynamic_string
--- Lower bound for a numeric setting. Combined with `max`, the setting renders as a slider.
---@field min? mod_settings.dynamic_number
--- Upper bound for a numeric setting. Combined with `min`, the setting renders as a slider.
---@field max? mod_settings.dynamic_number
--- Step between values for a slider and free-text number inputs. Defaults to 1.
--- H2M will clamp the input automatically.
---@field step? mod_settings.dynamic_number
--- Enum options: the values actually stored in the .cfg file.
--- Providing this makes the setting a cycler over these options.
---@field values? (string | number | boolean)[] | fun(): (string | number | boolean)[]
--- Display labels shown for each entry of `values` (same order, same number of entries). Each label may be a
--- localization table. When omitted, the raw values are shown in the cycler.
---@field labels? mod_settings.localized_string[] | fun(): mod_settings.localized_string[]
--- Sort key for custom ordering config entries in the menu, lower first.
--- When omitted, rows keep the order they are defined in the default config you provide.
---@field order? mod_settings.dynamic_number
--- Hide this setting from the menu entirely. Static only (evaluated when the menu builds) - for a
--- condition that changes while the menu is open, use `disabled`, which greys the setting out.
---@field hidden? boolean
--- Grey the setting out (shown read-only, cannot be changed) while this is true. Unlike `hidden`, a `disabled`
--- change updates live while the menu is open (e.g. grey a slider unless its parent toggle is enabled).
---@field disabled? mod_settings.dynamic_boolean
--- Description shown in place of `description` while the setting is greyed by its own `disabled` field, to
--- explain why it is unavailable. Ignored for a context-restricted row (only editable in main menu etc.) or
--- while the whole mod is disabled. Defaults to the normal `description` when omitted.
---@field disabledDescription? mod_settings.dynamic_string
--- Force a bounded number (one with `min` and `max`) to a free-text text field instead of a slider.
---@field freetext? boolean
--- Mark that changing this setting requires a game restart. The menu forces the player
--- to restart when they leave the mod menu after changing it.
---@field restartRequired? boolean
--- If this setting can be changed only in the main menu, only in a save (run or Crossroads), only in the Crossroads, or anywhere.
--- When the current context does not match, the row is shown read-only with a note.
--- The "enabled" setting and any `restartRequired` settings are always treated as `"mainMenu"`.
---@field editableContext? "any" | "mainMenu" | "inSave" | "inHub"
--- Append "%" to the displayed value.
---@field showAsPercentage? boolean
--- Display a 0..x value as 0..x00 *and* append "%" (the stored value stays 0..x).
---@field isPercentage? boolean
--- Called after this setting's value is changed through the in-game options menu, with the setting's key
--- and the new value. Use it to apply the change to the loaded run. It is not called in the main menu.
--- Re-writing the same value is a no-op and does not fire. Errors are logged, not propagated.
---@field onChange? fun(key: string, new_value: boolean|number|string)

--- An action button in the menu that runs a callback instead of editing a config value. Declare it as a
--- `configDesc` entry (with a matching key that has NO config value) carrying an `action` function.
---@class (exact) mod_settings.action_description
--- The callback run when the button is activated. Runs in your mod's environment.
---@field action fun()
--- Button label. Defaults to a prettified version of the key.
---@field displayName? mod_settings.dynamic_string
--- Help text shown while the button is highlighted.
---@field description? mod_settings.dynamic_string
--- Sort key among the section's rows, lower first.
---@field order? mod_settings.dynamic_number
--- When the button is activated: only in the main menu, only in a save (run or Crossroads), only in the Crossroads, or anywhere.
---@field editableContext? "any" | "mainMenu" | "inSave" | "inHub"
--- Grey the button out (non-interactive) while this is true. Updates live while the menu is open (e.g.
--- grey an "Apply" button until a value has actually changed).
---@field disabled? mod_settings.dynamic_boolean
--- Description shown in place of `description` while the setting is greyed by its own `disabled` field, to
--- explain why it is unavailable. Ignored for a context-restricted row (only editable in main menu etc.) or
--- while the whole mod is disabled. Defaults to the normal `description` when omitted.
---@field disabledDescription? mod_settings.dynamic_string

--- Each entry in `configDesc` can be a simple key:description string, a setting description table, an action
--- button, or a nested table of descriptions mirroring a config group. The underlying .cfg file contents are
--- not changed by this format.
---
--- Only keys with a `configDesc` entry are shown in the menu: a `config` key with no entry here is treated as
--- internal state and hidden (a group whose keys are all undescribed produces no row). The mod's master
--- `enabled` toggle is always shown regardless, so the mod stays toggleable.
---@alias mod_settings.config_desc table<string, mod_settings.setting_description | mod_settings.action_description | string | table>
